In [2]:
import pandas as pd
import numpy as np

In [23]:
#Load the dataset ../Data/eaglei_data/eaglei_outages_2014.csv
outages_2014 = pd.read_csv('../Data/eaglei_data/eaglei_outages_2014.csv')

In [24]:
#Convert the run_start_time variable into datetime
outages_2014['run_start_time'] = pd.to_datetime(outages_2014['run_start_time'])
outages_2014.set_index('run_start_time', inplace=True)

In [25]:
#Fill in missing timestamps every 15 minutes.
outages_2014_ffill = outages_2014.resample('15T').ffill()

/var/folders/gs/h69vjsl512b8200d29lxpgrc0000gn/T/ipykernel_87745/3580612881.py:2: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  outages_2014_ffill = outages_2014.resample('15T').ffill()

ValueError: cannot reindex on an axis with duplicate labels

In [18]:
#Display outages_2014 for county==Coosa and the date November 1 2014
outages_2014.loc[(outages_2014['county']=='Sagadahoc') & (outages_2014.index.date == pd.Timestamp('2014-12-01').date())].head(50)

                     fips_code     county  state  customers_out
run_start_time
2014-12-01 00:00:00      23023  Sagadahoc  Maine             22
2014-12-01 00:15:00      23023  Sagadahoc  Maine             25
2014-12-01 00:30:00      23023  Sagadahoc  Maine             25
2014-12-01 00:45:00      23023  Sagadahoc  Maine             25
2014-12-01 01:00:00      23023  Sagadahoc  Maine             25
2014-12-01 01:15:00      23023  Sagadahoc  Maine             25
2014-12-01 01:30:00      23023  Sagadahoc  Maine             25
2014-12-01 01:45:00      23023  Sagadahoc  Maine             25
2014-12-01 02:00:00      23023  Sagadahoc  Maine             25
2014-12-01 04:30:00      23023  Sagadahoc  Maine              1
2014-12-01 04:45:00      23023  Sagadahoc  Maine              1
2014-12-01 16:45:00      23023  Sagadahoc  Maine              1
2014-12-01 17:00:00      23023  Sagadahoc  Maine              1
2014-12-01 19:15:00      23023  Sagadahoc  Maine              1
2014-12-01 19:30:00      23023  Sagadahoc  Maine              1
2014-12-01 19:45:00      23023  Sagadahoc  Maine              1

In [ ]:
#Downsample outages_2014 to 6-hour time intervals from the run_start_time variable, taking the average value of the customers_out variable and using the first value for other variables
outages_2014_resampled = outages_2014.resample('6H').agg({'customers_out': np.mean, 'fips_code': 'first', 'county': 'first', 'state': 'first'})

/var/folders/gs/h69vjsl512b8200d29lxpgrc0000gn/T/ipykernel_87745/1547093158.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  outages_2014 = outages_2014.resample('6H').agg({'customers_out': np.mean, 'fips_code': 'first', 'county': 'first', 'state': 'first'})
/var/folders/gs/h69vjsl512b8200d29lxpgrc0000gn/T/ipykernel_87745/1547093158.py:4: FutureWarning: The provided callable <function mean at 0x1070c19e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  outages_2014 = outages_2014.resample('6H').agg({'customers_out': np.mean, 'fips_code': 'first', 'county': 'first', 'state': 'first'})

In [6]:
outages_2014.head(20)

                     customers_out  fips_code      county     state
run_start_time
2014-11-01 00:00:00     244.818966       1037       Coosa   Alabama
2014-11-01 06:00:00     254.085738       1013      Butler   Alabama
2014-11-01 12:00:00     232.398267       4017      Navajo   Arizona
2014-11-01 18:00:00     156.258418       1109        Pike   Alabama
2014-11-02 00:00:00      89.939597       5003      Ashley  Arkansas
2014-11-02 06:00:00     108.274401       1085     Lowndes   Alabama
2014-11-02 12:00:00     224.959500       5021        Clay  Arkansas
2014-11-02 18:00:00     363.102011       5039      Dallas  Arkansas
2014-11-03 00:00:00     554.094522       5017      Chicot  Arkansas
2014-11-03 06:00:00     713.864836       5143  Washington  Arkansas
2014-11-03 12:00:00     339.644319       5055      Greene  Arkansas
2014-11-03 18:00:00     289.021325       1003     Baldwin   Alabama
2014-11-04 00:00:00     413.556299       5001    Arkansas  Arkansas
2014-11-04 06:00:00     540.309655       5077         Lee  Arkansas
2014-11-04 12:00:00     231.405950       5037       Cross  Arkansas
2014-11-04 18:00:00     171.837292       1003     Baldwin   Alabama
2014-11-05 00:00:00     193.766667       5037       Cross  Arkansas
2014-11-05 06:00:00     302.424689       1031      Coffee   Alabama
2014-11-05 12:00:00     137.573174       5027    Columbia  Arkansas
2014-11-05 18:00:00     108.488357       1003     Baldwin   Alabama